spring:
  application:
    name: spring
  security:
    user:
      name: hamza
      password: 123
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/student
    username: postgres
    password: hamza